version: '3.4'

services:
  serversideapi:
    image: ${DOCKER_REGISTRY-}serversideapi
    build: .
    ports:
        - "8000:80"
    depends_on:
        - db
     

  db: 
      image: "mcr.microsoft.com/azure-sql-edge"
      environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"